#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

final_space = true
version = 2
shell_integration = true
console_title_template = "{{ .Shell } in {{ .Folder }}"

[[blocks]]
  alignment = 'left'
  newline = true
  type = 'prompt'

  [[blocks.segments]]
    background = 'transparent'
    foreground = 'p:blue'
    style = 'plain'
    template = '{{ .Path }}'
    type = 'path'

    [blocks.segments.properties]
      folder_icon = '…'
      folder_separator_icon = '/'
      mapped_locations_enabled = true
      max_width = 40
      style = 'powerlevel'

  [[blocks.segments]]
    background = 'transparent'
    foreground = 'p:overlay1'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}p:lavander{{ end }}',
      '{{ if gt .Behind 0 }}p:lavander{{ end }}',
    ]
    style = 'plain'
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} │{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} '
    type = 'git'

    [blocks.segments.properties]
      branch_ahead_icon = '↑'
      branch_behind_icon = '↓'
      branch_gone = '≢'
      branch_icon = ' '
      branch_identical_icon = '≡'
      cherry_pick_icon = '✓ '
      commit_icon = '▷ '
      fetch_stash_count = true
      fetch_status = true
      merge_icon = '◴ '
      no_commits_icon = '[no commits]'
      rebase_icon = 'Ɫ '
      tag_icon = '▶ '


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'


  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '  {{ .FormattedMs }}'

[[blocks]]
  alignment = 'left'
  newline = true
  type = 'prompt'

  [[blocks.segments]]
    background = 'transparent'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:mauve{{end}}",
    ]
    style = 'plain'
    template = '❯'
    type = 'text'

[transient_prompt]
  background = 'transparent'
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:mauve{{end}}",
  ]
  template = '❯ '

[secondary_prompt]
  background = "transparent"
  foreground = "p:green"
  template = "❯❯ "

[palette]
  rosewater = '#f4dbd6'
  flamingo = '#f0c6c6'
  pink = '#f5bde6'
  mauve = '#c6a0f6'
  red = '#ed8796'
  maroon = '#ee99a0'
  peach = '#f5a97f'
  yellow = '#eed49f'
  green = '#a6da95'
  teal = '#8bd5ca'
  sky = '#91d7e3'
  sapphire = '#7dc4e4'
  blue = '#8aadf4'
  lavender = '#b7bdf8'
  text = '#cad3f5'
  subtext1 = '#b8c0e0'
  subtext0 = '#a5adcb'
  overlay2 = '#969ab7'
  overlay1 = '#8087a2'
  overlay0 = '#6e738d'
  surface2 = '#5b6078'
  surface1 = '#494d64'
  surface0 = '#363a4f'
  base = '#24173a'
  mantle = '#1e2030'
  crust = '#181926'
