console_title_template = '{{ .Shell } in {{ .Folder }}'
version = 3
shell_integration = true
final_space = true

[palette]
  base = '#24173a'
  blue = '#8aadf4'
  crust = '#181926'
  flamingo = '#f0c6c6'
  green = '#a6da95'
  lavender = '#b7bdf8'
  mantle = '#1e2030'
  maroon = '#ee99a0'
  mauve = '#c6a0f6'
  overlay0 = '#6e738d'
  overlay1 = '#8087a2'
  overlay2 = '#969ab7'
  peach = '#f5a97f'
  pink = '#f5bde6'
  red = '#ed8796'
  rosewater = '#f4dbd6'
  sapphire = '#7dc4e4'
  sky = '#91d7e3'
  subtext0 = '#a5adcb'
  subtext1 = '#b8c0e0'
  surface0 = '#363a4f'
  surface1 = '#494d64'
  surface2 = '#5b6078'
  teal = '#8bd5ca'
  text = '#cad3f5'
  yellow = '#eed49f'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:green'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = [
    '{{if gt .Code 0}}p:red{{end}}',
    '{{if eq .Code 0}}p:mauve{{end}}',
  ]

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }}'
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '…'
      folder_separator_icon = '/'
      mapped_locations_enabled = true
      max_width = 40
      style = 'powerlevel'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} │{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} '
    foreground = 'p:overlay1'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}p:lavander{{ end }}',
      '{{ if gt .Behind 0 }}p:lavander{{ end }}',
    ]

    [blocks.segments.properties]
      branch_ahead_icon = '↑'
      branch_behind_icon = '↓'
      branch_gone = '≢'
      branch_icon = ' '
      branch_identical_icon = '≡'
      cache_duration = 'none'
      cherry_pick_icon = '✓ '
      commit_icon = '▷ '
      fetch_stash_count = true
      fetch_status = true
      merge_icon = '◴ '
      no_commits_icon = '[no commits]'
      rebase_icon = 'Ɫ '
      tag_icon = '▶ '

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '  {{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .UserName }}'
    foreground = 'p:sky'
    background = 'transparent'
    type = 'text'
    style = 'plain'

  [[blocks.segments]]
    template = '@{{ .HostName }} '
    foreground = 'p:overlay1'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{if gt .Code 0}}p:red{{end}}',
      '{{if eq .Code 0}}p:mauve{{end}}',
    ]

    [blocks.segments.properties]
      cache_duration = 'none'
